CREATE TABLE rol (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,

    CONSTRAINT pk_rol PRIMARY KEY (id_rol),
    CONSTRAINT uk_rol_nombre UNIQUE (nombre)
);


CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100),
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    id_rol BIGINT NOT NULL,

    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuario_username UNIQUE (username),

    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (id_rol)
        REFERENCES rol(id_rol)
);


CREATE TABLE categoria (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_categoria PRIMARY KEY (id_categoria),
    CONSTRAINT uk_categoria_nombre UNIQUE (nombre)
);


CREATE TABLE producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(255),
    precio NUMERIC(12,2) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    id_categoria BIGINT NOT NULL,

    CONSTRAINT pk_producto PRIMARY KEY (id_producto),
    CONSTRAINT uk_producto_codigo UNIQUE (codigo),

    CONSTRAINT ck_producto_precio
        CHECK (precio >= 0),

    CONSTRAINT fk_producto_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categoria(id_categoria)
);


CREATE TABLE stock (
    id_stock BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_producto BIGINT NOT NULL,
    cantidad INTEGER NOT NULL DEFAULT 0,
    stock_minimo INTEGER NOT NULL DEFAULT 5,

    CONSTRAINT pk_stock PRIMARY KEY (id_stock),
    CONSTRAINT uk_stock_producto UNIQUE (id_producto),

    CONSTRAINT ck_stock_cantidad
        CHECK (cantidad >= 0),

    CONSTRAINT ck_stock_minimo
        CHECK (stock_minimo >= 0),

    CONSTRAINT fk_stock_producto
        FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
);


CREATE TABLE venta (
    id_venta BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total NUMERIC(12,2) NOT NULL DEFAULT 0,
    id_usuario BIGINT NOT NULL,

    CONSTRAINT pk_venta PRIMARY KEY (id_venta),

    CONSTRAINT ck_venta_total
        CHECK (total >= 0),

    CONSTRAINT fk_venta_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);


CREATE TABLE detalle_venta (
    id_detalle_venta BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_venta BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL,

    CONSTRAINT pk_detalle_venta PRIMARY KEY (id_detalle_venta),

    CONSTRAINT ck_detalle_venta_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT ck_detalle_venta_precio
        CHECK (precio_unitario >= 0),

    CONSTRAINT ck_detalle_venta_subtotal
        CHECK (subtotal >= 0),

    CONSTRAINT fk_detalle_venta_venta
        FOREIGN KEY (id_venta)
        REFERENCES venta(id_venta),

    CONSTRAINT fk_detalle_venta_producto
        FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
);


CREATE TABLE compra (
    id_compra BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total NUMERIC(12,2) NOT NULL DEFAULT 0,
    id_usuario BIGINT NOT NULL,

    CONSTRAINT pk_compra PRIMARY KEY (id_compra),

    CONSTRAINT ck_compra_total
        CHECK (total >= 0),

    CONSTRAINT fk_compra_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);


CREATE TABLE detalle_compra (
    id_detalle_compra BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_compra BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL,

    CONSTRAINT pk_detalle_compra PRIMARY KEY (id_detalle_compra),

    CONSTRAINT ck_detalle_compra_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT ck_detalle_compra_precio
        CHECK (precio_unitario >= 0),

    CONSTRAINT ck_detalle_compra_subtotal
        CHECK (subtotal >= 0),

    CONSTRAINT fk_detalle_compra_compra
        FOREIGN KEY (id_compra)
        REFERENCES compra(id_compra),

    CONSTRAINT fk_detalle_compra_producto
        FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
);


CREATE TABLE movimiento_inventario (
    id_movimiento BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_producto BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    cantidad INTEGER NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    descripcion VARCHAR(255),

    CONSTRAINT pk_movimiento_inventario
        PRIMARY KEY (id_movimiento),

    CONSTRAINT ck_movimiento_tipo
        CHECK (tipo IN ('ENTRADA', 'SALIDA', 'AJUSTE')),

    CONSTRAINT ck_movimiento_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT fk_movimiento_producto
        FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto),

    CONSTRAINT fk_movimiento_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);